title: Zhonghao Lin's Homepage
page-top-title: Zhonghao Lin
top-section-bg-text: Computer Science
home-subtitle: Zhonghao Lin&ensp;|&ensp;林 忠豪
copyright-text: '&copy; Zhonghao Lin 2025-2028. All Rights Reserved.'
